# This is a basic workflow to help you get started with Actions

name: docker CI

# Controls when the workflow will run
on:
  # Triggers the workflow on release events
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      IMAGE_NAME: tierpsy-tracker
    steps:
      - name: check out repo code
        uses: actions/checkout@v2
      - name: docker login, build, tag, and push
        run: |
          if [[ -z $RELEASE_TAG ]]
          then
          tagname=$(python -c "from tierpsy.version import __version__; print(__version__.replace('+', '_'))")
          else
          tagname=$RELEASE_TAG
          fi
          echo "${tagname}"
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN
          docker build -t $IMAGE_NAME . -f docker/Dockerfile
          docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME:latest
          docker push $DOCKER_USER/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME:"${tagname}"
          docker push $DOCKER_USER/$IMAGE_NAME:"${tagname}"


